version: '3'
services:
  app:
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: "./web"
        target: "/var/www/html"
    ports:
      - "80:80"
    depends_on:
      - db
  db:
    image: mariadb:10.7.7-focal
    volumes:
      - type: bind
        source: "./mariadb/data"
        target: "/var/lib/mysql"
    ports:
      - "3306:3306"
    environment:
      # MySQLのイメージを使用するなら、環境変数は「MYSQL_ROOT_PASSWORD」に。
      - MARIADB_ROOT_PASSWORD=myrootpassword

